package model;

/**
 * Created by joshuazeltser on 18/01/2017.
 */
public enum RuleType {

    AND_INTRO, IMPLIES_INTRO, ASSUMPTION, GIVEN, AND_ELIM, OR_INTRO, NOT_ELIM, IMPLIES_ELIM, ONLY_ELIM, ONLY_INTRO,
    NOT_INTRO, OR_ELIM, INVALID, DOUBLE_NOT_ELIM, TICK
}
